# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Zhenting Qi
name: Zhenting Qi
position: Graduate Student 
email: zhentingqi@g.harvard.edu
description: >-
  I am a CS PhD student at [Harvard University](https://www.harvard.edu/), working with Prof. [Yilun Du](https://yilundu.github.io/) and Prof. [Hima Lakkaraju](https://himalakkaraju.github.io/). Prior to Harvard, I received master's degree in Computational Science and Engineering from Harvard, and dual bachelor's degree in Computer Engineering from both [UIUC](https://illinois.edu/) and [ZJU](https://www.zju.edu.cn/english/) with highest honors.


  Previously, I was a student researcher at Yale advised by (the late) Prof. [Dragomir R. Radev](http://www.cs.yale.edu/homes/radev/), and at UIUC advised by Prof. [Volodymyr Kindratenko](https://ece.illinois.edu/about/directory/faculty/kindrtnk). I also interned at [Microsoft Research Asia](https://www.microsoft.com/en-us/research/lab/microsoft-research-asia/), advised by Dr. [Li Lyna Zhang](https://www.microsoft.com/en-us/research/people/lzhani/). I also worked closely with Prof. [James Glass](https://sls.csail.mit.edu/people/glass.shtml) at MIT.
  

  Our group is open to collaborations! Please contact me at zhentingqi[AT]g[DOT]harvard[DOT]edu.

misc: >-
  I enjoy playing basketball/badminton, training, reading, cooking, movies, and I am a huge fan of guitar and music!

research: >-
  My research interest lies broadly in Language Modeling and Generative AI. My long-term research goal is to build intelligent and reliable AI systems for the benefit of human society. Motivated by this goal, I am currently interested in the following topics (w/o particular order)
  

  1) Reasoning: Why do current reasoning paradigms work and how do we improve them? How can we design AI systems to perform robust reasoning that generalizes well to out-of-distribution scenarios?


  2) Reliability: How do we better understand AI systems and further enhance their controllability and robustness? How can we design scalable method to ensure their safety while we are improving their capabilities?


  For more information, please see [Google Scholar](https://scholar.google.com/citations?hl=en&user=WZ00HCUAAAAJ), [Semantic Scholar](https://www.semanticscholar.org/author/Zhenting-Qi/2186056193) and [DBLP](https://dblp.org/pid/329/2118.html).

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zhentingqi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ZhentingQi
github_username: zhentingqi
google_scholar: WZ00HCUAAAAJ
# google_analytics: G-MFWSBLRKG0

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
